# Generated by Django 5.1.4 on 2025-01-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_library', '0002_document_updated_at_document_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_name',
            new_name='owner',
        ),
    ]
