# Generated by Django 5.1.4 on 2025-01-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_library', '0003_rename_user_name_document_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='version_history',
        ),
        migrations.AddField(
            model_name='document',
            name='version_count',
            field=models.IntegerField(default=1),
        ),
    ]
